import type { Metadata } from "next";
import { Lato, Montserrat, Poppins } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Surf Shop",
  //TODO: Add a description
  description: "Generated by create next app"
};

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat"
});

const poppins = Poppins({
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins"
});

const lato = Lato({
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-lato"
});

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} ${poppins.className} ${lato.className}`}
      >
        {children}
      </body>
    </html>
  );
}
